spring:
  application:
    name: zuul
server:
  port: 8080

eureka:
    instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
      prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://172.17.0.2:8080/eureka/
zuul:
  prefix: /api
  routes:
    producer:
      path: /producer/**
      serviceId: producer

    worker:
      path: /worker/**
      serviceID: worker

#zuul:
#  prefix: /api
#  routes:
#    producer:
#      path: /producer/**
#      url: http://172.17.0.4:8080




